### ISSUE TITLE
Expand fail

### ISSUE THREAD

**Issue by yougs** [Deyda/Microsoft#3]
Hi, i try this script to expand some vhdx O365 disk but i have this error and half work is doing : 

TerminatingError(Get-Partition): "Cannot validate argument on parameter 'DiskNumber'. The argument is null. Provide a valid value for the argument, and then try running the command again."
>> TerminatingError(Get-Partition): "Cannot validate argument on parameter 'DiskNumber'. The argument is null. Provide a valid value for the argument, and then try running the command again."
Cannot validate argument on parameter 'DiskNumber'. The argument is null. Provide a valid value for the argument, and then try running the command again.[0].Exception.GetType().FullName

My vhdx mounted with add 10Gb but no expand done 

![image](https://user-images.githubusercontent.com/76214899/106268092-e67c8200-622a-11eb-9dea-006a42042329.png)

**Comment by Deyda** [comment]
Thx for your respond. I will test it in my environment and give you feedback ;-)

**Comment by yougs** [comment]
thanks for your help i wait your answer.

**Comment by yougs** [comment]
more précision : 
i tested on c: location and it works fine. but when i test en z: location (fileshare azure mounted as Z:) i receive error below.

**Comment by yougs** [comment]
Work fine with full unc path \\azuredestination\pathvhdcontainer
