### ISSUE TITLE
Have to run script twice to shrink VHD

### ISSUE THREAD

**Issue by JasonP7600** [Deyda/Microsoft#5]
I have noticed that trying to compress some disks they are not compressing to what I expected them to. I have tested this a few times and get the same issue.

Example:
User had a 20GB VHD 
Ran your script once gave this output :
Post Defragmentation Report:
VERBOSE:
 Volume Information:
VERBOSE:   Volume size                 = 29.29 GB
VERBOSE:   Cluster size                = 4 KB
VERBOSE:   Used space                  = 2.18 GB
VERBOSE:   Free space                  = 27.10 GB
VERBOSE:
 Allocation Units:
VERBOSE:   Slab count                  = 936
VERBOSE:   Slab size                   = 32 MB
VERBOSE:   Slab alignment              = 31.00 MB
VERBOSE:   In-use slabs                = 73
VERBOSE:
 Slab Consolidation:
VERBOSE:   Space efficiency            = 100%
VERBOSE:   Potential purgable slabs    = 430
VERBOSE:   Slabs pinned unmovable      = 6
VERBOSE:   Successfully purged slabs   = 423
VERBOSE:   Recovered space             = 13.21 GB
VERBOSE:
 Retrim:
VERBOSE:   Backed allocations          = 618
VERBOSE:   Allocations trimmed         = 545
VERBOSE:   Total space trimmed         = 17.03 GB

but looking at the VHD it was only dropped back to 11GB.

I ran the script again and it dropped the VHD down to 2GB with this output :
Post Defragmentation Report:
VERBOSE:
 Volume Information:
VERBOSE:   Volume size                 = 29.29 GB
VERBOSE:   Cluster size                = 4 KB
VERBOSE:   Used space                  = 2.18 GB
VERBOSE:   Free space                  = 27.10 GB
VERBOSE:
 Allocation Units:
VERBOSE:   Slab count                  = 936
VERBOSE:   Slab size                   = 32 MB
VERBOSE:   Slab alignment              = 31.00 MB
VERBOSE:   In-use slabs                = 73
VERBOSE:
 Slab Consolidation:
VERBOSE:   Space efficiency            = 100%
VERBOSE:   Potential purgable slabs    = 0
VERBOSE:   Slabs pinned unmovable      = 6
VERBOSE:   Successfully purged slabs   = 0
VERBOSE:   Recovered space             = 0 bytes
VERBOSE:
 Retrim:
VERBOSE:   Backed allocations          = 73
VERBOSE:   Allocations trimmed         = 0
VERBOSE:   Total space trimmed         = 0 bytes

Is this expected behaviour ? Do I have to run the script twice for it to finally truncate the VHD to the correct size ?

**Comment by Deyda** [comment]
Yes, this is a normal behavior when starting the optimization. 
At the beginning you should run the script several times. Afterwards it is enough to run it daily over night.

**Comment by JasonP7600** [comment]
If you mean by daily, then (I have not tested), but is it able to do this while a user has an open session or does it need to be a closed session (as in the user is logged off) ?

**Comment by Deyda** [comment]
Yes I mean daily at night, as it can only optimize closed containers that are no longer in use.

**Comment by JasonP7600** [comment]
Thanks for confirming. Our sessions can stay open for days. So we will plan for these during scheduled maintenance
