### ISSUE TITLE
Missing lines from original Version

### ISSUE THREAD

**Issue by stdanro** [Deyda/Microsoft#6]
I tried this version https://github.com/Deyda/Microsoft/blob/master/FSLogix/FSLogix-ShrinkDisk.ps1
but I'm getting errors and disk's stay mounted after error.

can you import missing lines from https://github.com/FSLogix/Invoke-FslShrinkDisk/blob/master/Invoke-FslShrinkDisk.ps1

**Comment by Deyda** [comment]
There are no lines missing. Everything works for me. Please send the logs and a screenshot. 

It is the same script as from Jim Moyle, only in mine there are additional functions stored, which my customers need.

**Comment by stdanro** [comment]
> There are no lines missing. Everything works for me. Please send the logs and a screenshot.
> 
> It is the same script as from Jim Moyle, only in mine there are additional functions stored, which my customers need.

Here you go: Hope this helps
Disks stay mounted after script crash
![image](https://user-images.githubusercontent.com/44283904/110116969-8d1eea00-7db8-11eb-85b7-98cef128467a.png)
![image](https://user-images.githubusercontent.com/44283904/110116999-97d97f00-7db8-11eb-918e-8c6299884905.png)
